# Generated by Django 3.2.9 on 2021-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(related_name='hash_post', to='my_post_app.HashTag'),
        ),
    ]
